### ISSUE TITLE
matscholar website is down - example text?

### ISSUE THREAD

**Issue by flckv** [lbnlp/NERRE#7]
Can you give an example text that is returned by the link you provided, please? 
[https://matscholar.com/api/search/?query={parse.quote(ferrimagnetic)}&type=all&restrict=doc&hits=1](https://matscholar.com/api/search/?query=%7Bparse.quote(ferrimagnetic)%7D&type=all&restrict=doc&hits=1)

![image](https://github.com/lbnlp/NERRE/assets/103381497/444fdf58-cdb9-4a70-abd9-87af3c90988e)

**Comment by jdagdelen** [comment]
Seems like the site is bck up.
